### ISSUE TITLE
Idea: remove ConstIndexLens and let StaticNumbers.jl handle it

### ISSUE THREAD

**Issue by tkf** [jw3126/Setfield.jl#119]
We can use `@lens _[static(1)]` instead of  `@lens _[$1]` <strike>once https://github.com/perrutquist/StaticNumbers.jl/issues/5 is fixed</strike> (edit: fixed by https://github.com/perrutquist/StaticNumbers.jl/pull/6).  I think this is good as it frees `$` from the lens syntax which may be useful for something else (e.g., `@set first($xs) = x` to do `set(xs, (@lens first(_)), x)`).

**Comment by jw3126** [comment]
Would be great to get rid of the `ConstIndexLens`! For this to we don't need to implement anything (expect tests right)?

**Comment by tkf** [comment]
Yeah, just remove the code. Best kind of patch :)
