### ISSUE TITLE
Nitpicking: use isequal instead of == in lens law documentation

### ISSUE THREAD

**Issue by tkf** [jw3126/Setfield.jl#133]
`==` in Julia does some interesting things:

```julia
julia> NaN == NaN
false

julia> missing == missing
missing

julia> I(2) == I == I(3)
true
```

**Comment by jw3126** [comment]
Yeah, the meaning of equality is always subtle. I agree `isequal` is more safe. But it is also less readable. Also with lenses involving floating point I often have cases, where equality is only approximate: 
```julia
get(set(obj, lens, x)) ≈ x
```
So maybe we could add a remark to the docs, that depending on the context other notions of equality like `isequal` may be more appropriate?

**Comment by tkf** [comment]
Yeah, I agree with everything you mentioned. I guess using some non-standard unicode infix comparison would look nice in the documentation.

(I should be documenting this in Kaleido.jl as some of the lenses there definitely do not satisfy the lens law with `isless`.)

**Comment by jw3126** [comment]
How about `\cong ≅`?
