### ISSUE TITLE
@set or setproperties for parametric struct/type?

### ISSUE THREAD

**Issue by jlchan** [jw3126/Setfield.jl#152]
I'm getting errors with `@set` and `setproperties` for parametric structs/types. Is there a way around this in Setfield?
```julia
using Setfield
struct Foo{T}; a; end
x = Foo{1}(2)
@set x.a = 20 # fails
setproperties(x,(a=20)) # fails
```

**Comment by jw3126** [comment]
Yes there is! When doing `setproperties(obj::MyType{A,B,C}, patch::NamedTuple)` the default is to just remove the type params and call `MyType(patch...)` . You can customize this using [ConstructionBase](https://juliaobjects.github.io/ConstructionBase.jl/stable/)
In more complicated cases, also feel free to overload `ConstructionBase.setproperties(::MyType, ::NamedTuple)` directly.

```julia
using ConstructionBase
using Setfield
struct Foo{T}; a; end

ConstructionBase.constructorof(::Type{Foo{T}}) where {T} = Foo{T}

x = Foo{1}(2)
@set x.a = 20
```

**Comment by jlchan** [comment]
That works great - thank you!

**Comment by jlchan** [comment]
Just to check, is it not possible to adapt this approach to type aliases? 
```julia
using ConstructionBase
using Setfield
struct Foo{T1,T2}; a; end
const Foo{T1} = Foo{T1,T2} where {T2}
ConstructionBase.constructorof(::Type{Foo{T1}}) where {T1} = Foo{T1}
```
My impression is no, that the `where {T2}` in the type alias will cause issues...

**Comment by jw3126** [comment]
By default `setproperties` will call `constructorof(typeof(obj))`. Note that `typeof(obj)` is a concrete type, it can be `Foo{Int, String}`, but it can never be `Foo{Int}`. So the method you defined is never called. 
Instead you need to overload `ConstructionBase.constructorof(::Type{Foo{T1, T2}}) where {T1, T2}`. Does that help?

**Comment by jw3126** [comment]
Whether or not define any aliases for a type is irrelevant.

**Comment by jlchan** [comment]
Yup, that makes sense. Thanks for explaining the concrete type stuff, I've seen them but hadn't worked with them before. It's helpful to see how the internals work together.
