### ISSUE TITLE
`DynamicIndexLens` for `begin`?

### ISSUE THREAD

**Issue by phipsgabler** [jw3126/Setfield.jl#154]
```julia
julia> @lens _[end]
Setfield.DynamicIndexLens{var"#1#2"}(var"#1#2"())

julia> @lens _[begin]
ERROR: UndefVarError: begin not defined
Stacktrace:
 [1] top-level scope at REPL[6]:1
```

I presume this line:

https://github.com/jw3126/Setfield.jl/blob/544346fce31eb904a951eb651e69fe0fe24490b2/src/sugar.jl#L66

should also contain a test for `:begin`, right?

**Comment by jw3126** [comment]
Oh wow thanks a lot for reporting, interesting that this went unnoticed so long!
