### ISSUE TITLE
Possibility of loosening type-strict equality of indices

### ISSUE THREAD

**Issue by phipsgabler** [jw3126/Setfield.jl#165]
The problem I have is this:

```julia
julia> @lens(_[1:10]) == @lens(_[Base.OneTo(10)])
false

julia> @lens(_[1:10]).indices == @lens(_[Base.OneTo(10)]).indices
true
```

arising from the dispatch on a common type in [the definition](https://github.com/jw3126/Setfield.jl/blob/d8938be8f715e570835a8db24951e0a974c90fbe/src/lens.jl#L196):

```julia
==(l1::IndexLens{I}, l2::IndexLens{I}) where {I} = l1.indices == l2.indices
```

I'm asking if there's a possibility of loosening this to

```julia
==(l1::IndexLens, l2::IndexLens) = l1.indices == l2.indices
```

(and the same for `ComposedLens`).  I think this is sensible, since if index values are considered equal, they (hopefully) should also index to equal things.

(I am to [blame for this](https://github.com/jw3126/Setfield.jl/blame/d8938be8f715e570835a8db24951e0a974c90fbe/src/lens.jl#L196) my self anyway :P)

**Comment by jw3126** [comment]
Yes this sounds reasonable.
