### ISSUE TITLE
set many fields at once

### ISSUE THREAD

**Issue by rveltz** [jw3126/Setfield.jl#80]
Hi,

Is the following a low hanging fruit?

Thank you for your very useful package(s)    ;D

```julia
A = (a=1,b=2,c=3)
B = @set A.a=1.0

# This does not work....
C = @set A.a=1.0 A.b = -1.0
```

**Comment by tkf** [comment]
It is a frequently requested feature :)

Quoting @jw3126 in https://github.com/jw3126/Setfield.jl/issues/62#issuecomment-469632630:

> A lot of people including myself want it. The problem is that somebody actually has to implement it .

See also: https://github.com/jw3126/Setfield.jl/issues/74

**Comment by rveltz** [comment]
`setproperties` is good [enough](https://github.com/jw3126/Setfield.jl/issues/62#issuecomment-469632630)!!!

I had not seen it.
