### ISSUE TITLE
Confusing error from @lens _.[:a]

### ISSUE THREAD

**Issue by tkf** [jw3126/Setfield.jl#83]
```julia
julia> @lens _[:a]
(@lens _[:a])

julia> @lens _.[:a]
ERROR: TypeError: in Type, in parameter, expected Type, got Expr
Stacktrace:
 [1] top-level scope at REPL[36]:1

julia> @macroexpand @lens _.[:a]
:(Setfield.compose(Setfield.PropertyLens{$(QuoteNode(:([:a])))}()))
```

Note the `.` before `[:a]`.

**Comment by jw3126** [comment]
Was the `@lens _.[:a]` a typo or did you expect any particular semantics?

**Comment by tkf** [comment]
Sorry, I should've clarified that it was about error handling. I think it would be nice to throw an error inside the macro.

(We probably can add some meaning to it after Julia adds getindex broadcasting.)

**Comment by jw3126** [comment]
I think we simply need to check if `property` is a `Symbol`:
https://github.com/jw3126/Setfield.jl/blob/854fb3dd4c6b94489029a94c7e6e23590c8bb539/src/sugar.jl#L72

**Comment by tkf** [comment]
We also need to allow `String`. I just mark it as `good first issue` (although maybe I'll do it at some point).

**Comment by jw3126** [comment]
Yeah, I already had kind of a bad feeling when I wrote `Symbol`. Good idea to label this first issue.

**Comment by jw3126** [comment]
#98
