### ISSUE TITLE
Setting properties

### ISSUE THREAD

**Issue by cstjean** [jw3126/Setfield.jl#90]
I'm interested in something like

```julia
@set object.property.x = 10
```

Can I support it? I get an error from `assert_hasfields` because, of course, `property` is not a field of `object`. I'd like to be able to implement `setproperty(::Object, value, sym)`, similar to `Base.setindex`, which would return a new object with that property modified. Is that possible?

**Comment by jw3126** [comment]
Yes! You need to overload `Setfield.setproperties(obj, patch::NamedTuple)`. In the next few days/weeks this is moved to the tiny dependency [ConstructionBase](https://github.com/JuliaObjects/ConstructionBase.jl), see also https://github.com/JuliaObjects/ConstructionBase.jl/pull/1
So in future you only need to depend on ConstructionBase and overload  `ConstructionBase.setproperties(obj, patch::NamedTuple)`

**Comment by jw3126** [comment]
See for an example here:
https://github.com/jw3126/Setfield.jl/blob/51bf0965e16bbb0a3abf5c97260bc7408eccb029/test/test_core.jl#L398

**Comment by cstjean** [comment]
It seems to work great, thank you!

**Comment by cstjean** [comment]
BTW, I haven't followed the entire discussion around `constructor_of`, but wouldn't it make sense to rewrite Setfield.jl around `setproperties`, with a fall-back to the constructor when it's not implemented? Relying on the constructor never felt quite right to me.

**Comment by jw3126** [comment]
I would say that `Setfield.jl` is already designed around `setproperties`. The default implementation just uses `constructor_of`. Try
```julia
Setfield.setproperties(MyType, patch) = ...
Setfield.constructor_of(::Type{<:MyType}) = error()
```
And `Setfield.jl` should work fine with `MyType`.
